# tickers.py
# Expanded categorized list of Japanese and US stock tickers with trend tags

JP_TICKERS = {
    # === AI・半導体関連 ===
    "9984.T": {"name": "ソフトバンクグループ", "tags": ["AI", "投資", "情報通信"]},
    "3778.T": {"name": "さくらインターネット", "tags": ["AI", "クラウド", "情報通信", "急騰期待"]},
    "6857.T": {"name": "アドバンテスト", "tags": ["AI", "半導体", "電気機器"]},
    "8035.T": {"name": "東京エレクトロン", "tags": ["半導体", "電気機器"]},
    "6526.T": {"name": "ソシオネクスト", "tags": ["半導体", "設計", "電気機器", "急騰期待"]},
    "6723.T": {"name": "ルネサスエレクトロニクス", "tags": ["半導体", "車載", "電気機器"]},
    "3993.T": {"name": "PKSHA Technology", "tags": ["AI", "情報通信", "急騰期待"]},
    "4011.T": {"name": "ヘッドウォータース", "tags": ["AI", "情報通信", "急騰期待"]},
    "4180.T": {"name": "Appier Group", "tags": ["AI", "マーケティング", "情報通信"]},
    "9613.T": {"name": "NTTデータ", "tags": ["AI", "ITサービス", "情報通信"]},
    "6702.T": {"name": "富士通", "tags": ["AI", "ITサービス", "電気機器"]},
    
    # === 宇宙開発・防衛関連 ===
    "7011.T": {"name": "三菱重工業", "tags": ["宇宙", "防衛", "航空重工", "機械"]},
    "7012.T": {"name": "川崎重工業", "tags": ["宇宙", "防衛", "航空宇宙", "輸送用機器"]},
    "7013.T": {"name": "IHI", "tags": ["宇宙", "航空宇宙", "ロケット", "機械"]},
    "9348.T": {"name": "ispace", "tags": ["宇宙", "月面開発", "サービス業", "急騰期待"]},
    "5595.T": {"name": "QPSホールディングス", "tags": ["宇宙", "衛星レーダー", "情報通信", "急騰期待"]},
    "6701.T": {"name": "日本電気 (NEC)", "tags": ["宇宙", "衛星システム", "電気機器"]},
    "7739.T": {"name": "キヤノン電子", "tags": ["宇宙", "精密機器"]},
    "9232.T": {"name": "パスコ", "tags": ["宇宙", "衛星データ分析", "情報通信"]},
    
    # === 爆発的急騰期待（グロース・中小型・高ベータ・バイオ） ===
    "5253.T": {"name": "カバー", "tags": ["急騰期待", "VTuber", "情報通信"]},
    "5032.T": {"name": "ANYCOLOR", "tags": ["急騰期待", "VTuber", "情報通信"]},
    "9166.T": {"name": "GENDA", "tags": ["急騰期待", "エンタメM&A", "サービス業"]},
    "9552.T": {"name": "M&A総研ホールディングス", "tags": ["急騰期待", "AI仲介", "サービス業"]},
    "2160.T": {"name": "ジーエヌアイグループ", "tags": ["急騰期待", "創薬バイオ", "医薬品"]},
    "4894.T": {"name": "クオリプス", "tags": ["急騰期待", "iPS創薬", "医薬品"]},
    "4592.T": {"name": "サンバイオ", "tags": ["急騰期待", "再生医療", "医薬品"]},
    "3697.T": {"name": "SHIFT", "tags": ["急騰期待", "品質保証", "サービス業"]},
    "7342.T": {"name": "ウェルスナビ", "tags": ["急騰期待", "フィンテック", "情報通信"]},
    "4165.T": {"name": "プレイド", "tags": ["急騰期待", "SaaS", "情報通信"]},
    "4478.T": {"name": "フリー", "tags": ["急騰期待", "SaaS", "情報通信"]},
    "3632.T": {"name": "グリー", "tags": ["急騰期待", "ゲーム・メタバース", "情報通信"]},
    
    # === 日本株主要大型（インフラ・金融・商社） ===
    "7203.T": {"name": "トヨタ自動車", "tags": ["自動車", "輸送用機器"]},
    "7267.T": {"name": "ホンダ (Honda)", "tags": ["自動車", "輸送用機器"]},
    "6758.T": {"name": "ソニーグループ", "tags": ["エンタメ", "電気機器"]},
    "6861.T": {"name": "キーエンス", "tags": ["センサー", "電気機器"]},
    "7974.T": {"name": "任天堂", "tags": ["ゲーム", "その他製品"]},
    "8306.T": {"name": "三菱UFJフィナンシャルG", "tags": ["銀行業", "金融"]},
    "8316.T": {"name": "三井住友フィナンシャルG", "tags": ["銀行業", "金融"]},
    "8411.T": {"name": "みずほフィナンシャルG", "tags": ["銀行業", "金融"]},
    "8766.T": {"name": "東京海上ホールディングス", "tags": ["保険業", "金融"]},
    "8058.T": {"name": "三菱商事", "tags": ["商社", "卸売業"]},
    "8031.T": {"name": "三井物産", "tags": ["商社", "卸売業"]},
    "8001.T": {"name": "伊藤忠商事", "tags": ["商社", "卸売業"]},
    "8002.T": {"name": "丸紅", "tags": ["商社", "卸売業"]},
    "9432.T": {"name": "日本電信電話 (NTT)", "tags": ["情報通信"]},
    "9433.T": {"name": "KDDI", "tags": ["情報通信"]},
    "4568.T": {"name": "第一三共", "tags": ["医薬品"]},
    "2914.T": {"name": "日本たばこ産業 (JT)", "tags": ["食料品", "高配当"]},
    "9101.T": {"name": "日本郵船", "tags": ["海運業"]},
    "9104.T": {"name": "商船三井", "tags": ["海運業"]},
    "9107.T": {"name": "川崎汽船", "tags": ["海運業"]},
    "8801.T": {"name": "三井不動産", "tags": ["不動産業"]},
    "8802.T": {"name": "三菱地所", "tags": ["不動産業"]},
    "9020.T": {"name": "JR東日本", "tags": ["陸運業"]},
    "9022.T": {"name": "JR東海", "tags": ["陸運業"]},
}

US_TICKERS = {
    # === AI・半導体関連 ===
    "NVDA": {"name": "NVIDIA Corporation", "tags": ["AI", "半導体"]},
    "MSFT": {"name": "Microsoft Corporation", "tags": ["AI", "ソフトウェア", "クラウド"]},
    "GOOGL": {"name": "Alphabet Inc.", "tags": ["AI", "検索", "クラウド"]},
    "META": {"name": "Meta Platforms, Inc.", "tags": ["AI", "SNS"]},
    "AVGO": {"name": "Broadcom Inc.", "tags": ["AI", "半導体"]},
    "AMD": {"name": "Advanced Micro Devices", "tags": ["AI", "半導体"]},
    "SMCI": {"name": "Super Micro Computer", "tags": ["AI", "サーバー", "急騰期待"]},
    "PLTR": {"name": "Palantir Technologies", "tags": ["AI", "ビッグデータ", "防衛", "急騰期待"]},
    "SOUN": {"name": "SoundHound AI, Inc.", "tags": ["AI", "音声認識", "急騰期待"]},
    "IONQ": {"name": "IonQ, Inc.", "tags": ["AI", "量子コンピュータ", "急騰期待"]},
    "AI": {"name": "C3.ai, Inc.", "tags": ["AI", "ソフトウェア", "急騰期待"]},
    
    # === 宇宙開発・防衛関連 ===
    "RKLB": {"name": "Rocket Lab USA", "tags": ["宇宙", "ロケット", "急騰期待"]},
    "LUNR": {"name": "Intuitive Machines", "tags": ["宇宙", "月面着陸", "急騰期待"]},
    "ASTS": {"name": "AST SpaceMobile", "tags": ["宇宙", "携帯衛星通信", "急騰期待"]},
    "SPIR": {"name": "Spire Global", "tags": ["宇宙", "衛星データ分析", "急騰期待"]},
    "PL": {"name": "Planet Labs PBC", "tags": ["宇宙", "地球画像観測"]},
    "LMT": {"name": "Lockheed Martin", "tags": ["宇宙", "防衛", "航空"]},
    "NOC": {"name": "Northrop Grumman", "tags": ["宇宙", "防衛"]},
    "GD": {"name": "General Dynamics", "tags": ["防衛", "航空宇宙"]},
    
    # === 爆発的急騰期待（暗号資産・ネットミーム・ハイベータ） ===
    "MSTR": {"name": "MicroStrategy Inc.", "tags": ["急騰期待", "ビットコイン保有", "ソフトウェア"]},
    "COIN": {"name": "Coinbase Global, Inc.", "tags": ["急騰期待", "暗号資産取引所", "金融テクノロジー"]},
    "MARA": {"name": "MARA Holdings (Marathon)", "tags": ["急騰期待", "暗号資産マイニング"]},
    "RIOT": {"name": "Riot Platforms, Inc.", "tags": ["急騰期待", "暗号資産マイニング"]},
    "GME": {"name": "GameStop Corp.", "tags": ["急騰期待", "ミーム株", "小売業"]},
    "AMC": {"name": "AMC Entertainment", "tags": ["急騰期待", "ミーム株", "映画興行"]},
    "DJT": {"name": "Trump Media & Tech Group", "tags": ["急騰期待", "政治関連", "SNS"]},
    "RDDT": {"name": "Reddit, Inc.", "tags": ["急騰期待", "SNS", "AI学習データ"]},
    "TEM": {"name": "Tempus AI, Inc.", "tags": ["急騰期待", "AI精密医療", "ヘルスケア"]},
    "JOBY": {"name": "Joby Aviation, Inc.", "tags": ["急騰期待", "空飛ぶクルマ", "航空宇宙"]},
    "ACHR": {"name": "Archer Aviation", "tags": ["急騰期待", "空飛ぶクルマ", "航空宇宙"]},
    "HOOD": {"name": "Robinhood Markets", "tags": ["急騰期待", "投資アプリ", "フィンテック"]},
    
    # === 米国主要大型株 ===
    "AAPL": {"name": "Apple Inc.", "tags": ["ハードウェア", "スマホ", "AI"]},
    "AMZN": {"name": "Amazon.com, Inc.", "tags": ["EC", "クラウド", "AI"]},
    "TSLA": {"name": "Tesla, Inc.", "tags": ["自動車", "EV", "AI", "自動運転", "急騰期待"]},
    "BRK-B": {"name": "Berkshire Hathaway", "tags": ["金融", "投資"]},
    "LLY": {"name": "Eli Lilly & Co.", "tags": ["バイオ", "製薬", "肥満症薬", "急騰期待"]},
    "UNH": {"name": "UnitedHealth Group", "tags": ["保険", "ヘルスケア"]},
    "JPM": {"name": "JPMorgan Chase & Co.", "tags": ["銀行", "金融"]},
    "V": {"name": "Visa Inc.", "tags": ["決済", "金融"]},
    "MA": {"name": "Mastercard Inc.", "tags": ["決済", "金融"]},
    "TSM": {"name": "Taiwan Semiconductor", "tags": ["半導体", "受託製造"]},
    "COST": {"name": "Costco Wholesale", "tags": ["小売"]},
    "HD": {"name": "Home Depot", "tags": ["小売", "住宅改善"]},
    "NFLX": {"name": "Netflix, Inc.", "tags": ["エンタメ", "ストリーミング"]},
    "WMT": {"name": "Walmart Inc.", "tags": ["小売"]},
    "DIS": {"name": "Walt Disney Company", "tags": ["エンタメ"]},
}
